base_url = "https://gyvm.github.io/blog-zola/"
title = "gyvm's blog"
description = "技術と趣味についてのブログ"
default_language = "en"
author = "yosuke mori"

compile_sass = true
minify_html = true
generate_feed = true
feed_filename = "atom.xml"

taxonomies = [
  { name = "tags", feed = true },
]

build_search_index = true

[markdown]
highlight_code = true
render_emoji = true

[extra]
links = [
    { title = "GitHub", href = "https://github.com/gyvm" },
    { title = "LinkedIn", href = "https://linkedin.com" }
]
